using System.Net;
using System.Net.Http;
using System.Security.Cryptography;
using Xunit;

namespace Pinhole.Tests;

public sealed class IrohConnectivityTests
{
    // Generated by the official iroh-ffi 1.1.0 EndpointTicket.from_addr. Includes
    // both address families and a postcard u16 port requiring three varint bytes.
    private const string NativeId = "03a107bff3ce10be1d70dd18e74bc09967e4d6309ba50d5f1ddc8664125531b8";
    private const string NativeTicket = "endpointaab2cb576phbbpq5odorrz2lycmwpzgwgcn2kdk7dxoimzaskuy3qayaejuhi5dqom5c6l3bobztcljrfzzgk3dbpexg4mbonfzg62bonruw42zpaeah6aaaagaaqaibaaaaaaaaaaaaaaaaaaaaaaaaah776ay";
    // Produced by native iroh-dns EndpointInfo.to_pkarr_signed_packet, not by this
    // implementation. Native DNS compression and repeated addr= records are covered.
    private const string NativePkarr = "5182e77a20ad8d14633a89ae1ecd54b6ed76876c46029d249550234f4828e5a38c099c2482f3f1941a314cd9d71135eee2eca8a44678290f172780daf240370400065d308086bd2c000080000000000300000000055f69726f683479716f6f787839753361656d68386d6f3577637171313679756675366a69746f7571316f347a613735316467657231696767687900001000010000003c00292872656c61793d68747470733a2f2f617073312d312e72656c61792e6e302e69726f682e6c696e6b2fc00c001000010000003c001413616464723d3132372e302e302e313a31303234c00c001000010000003c001110616464723d5b3a3a315d3a3635353335";
    private static readonly TimeSpan Budget = TimeSpan.FromSeconds(10);

    private static IrohTransportOptions Offline(byte[]? seed = null) => new()
    {
        PublishAddress = false,
        SecretKeySeed = seed,
        Network = new PinholeOptions
        {
            Bind = new IPEndPoint(IPAddress.Loopback, 0), StunServers = [], Relays = [], IrohRelayUrls = [],
            PublishIrohAddress = false,
            EnableLanDiscovery = false,
            EnableNetworkWatch = false, EnablePortMapping = false, StunRefreshInterval = TimeSpan.Zero,
        },
    };

    [Fact]
    public void NativeEndpointTicket_ParsesAndEncodesByteIdentically()
    {
        IrohAddress address = IrohAddress.Parse(NativeTicket);
        Assert.Equal(NativeId, address.EndpointId);
        Assert.Equal([new IPEndPoint(IPAddress.Loopback, 1024), new IPEndPoint(IPAddress.IPv6Loopback, 65535)], address.DirectAddresses);
        Assert.Equal(new Uri("https://aps1-1.relay.n0.iroh.link/"), Assert.Single(address.RelayUrls));
        Assert.Equal(NativeTicket, address.ToString());
        for (int i = 0; i < NativeTicket.Length; i++)
            Assert.Throws<FormatException>(() => IrohAddress.Parse(NativeTicket[..i]));
        Assert.Throws<FormatException>(() => IrohAddress.Parse(NativeTicket + "a"));
    }

    [Fact]
    public async Task NativeSecretSeed_RestoresTheExactIrohEndpointId()
    {
        await using var transport = await IrohTransport.BindAsync(Offline(Enumerable.Range(0, 32).Select(x => (byte)x).ToArray()));
        Assert.Equal(NativeId, transport.EndpointId);
        Assert.StartsWith("endpoint", transport.Address.ToString());
        Assert.False(transport.HasRelay);
    }

    [Fact]
    public void NativeSignedDiscoveryPacket_VerifiesAgainstThePinnedEndpointKey()
    {
        byte[] key = Convert.FromHexString(NativeId);
        byte[] wire = Convert.FromHexString(NativePkarr);
        IrohAddress address = IrohDiscovery.ParsePayload(key, wire, out ulong timestamp);
        Assert.Equal(NativeTicket, address.ToString());
        var seed = Enumerable.Range(0, 32).Select(x => (byte)x).ToArray();
        // Re-encode with the native timestamp: native Ed25519 signatures and DNS
        // serialization must match byte for byte, not merely our own decoder.
        Assert.Equal(wire, IrohDiscovery.CreatePayload(address, new RelayIdentity(seed), timestamp));
        wire[10] ^= 1;
        Assert.Throws<InvalidDataException>(() => IrohDiscovery.ParsePayload(key, wire, out _));
    }

    [Theory]
    [InlineData(0)]
    [InlineData(1)]
    [InlineData(9000)]
    [InlineData(60000)]
    public async Task RawUdp_ArbitraryPacketsAreUnchanged_IncludingPinholeTagsAndStunLikeBytes(int size)
    {
        await using var a = await IrohTransport.BindAsync(Offline());
        await using var b = await IrohTransport.BindAsync(Offline());
        IrohRoute route = await a.ConnectAsync(b.Address.ToString());
        byte[] payload = RandomNumberGenerator.GetBytes(size);
        if (size > 0) payload[0] = 0x50; // must not enter Pinhole's PUNC dispatcher
        if (size >= 20) new byte[] { 0x21, 0x12, 0xa4, 0x42 }.CopyTo(payload, 4);
        route.Send(payload);
        IrohDatagram received = await b.ReceiveAsync().AsTask().WaitAsync(Budget);
        Assert.Equal(payload, received.Payload.ToArray());
        Assert.Null(received.Path.EndpointId); // UDP source addresses are not authenticated endpoint IDs
        Assert.Equal(a.LocalPort, received.Path.DirectAddress!.Port);
        b.SendTo(received.Path, received.Payload.Span);
        Assert.Equal(payload, (await a.ReceiveAsync().AsTask().WaitAsync(Budget)).Payload.ToArray());
        Assert.Null(route.SelectedPath); // even a response cannot silently select an unauthenticated path
    }

    [Fact]
    public async Task RawUdp_NativeIPv4ThenIPv6_RestoresAddressCapacityAndKeepsReceiving()
    {
        using var net = new VirtualNetwork();
        var receiverSocket = new VirtualUdpSocket(net, new IPEndPoint(IPAddress.Parse("198.51.100.20"), 30020), null)
        {
            NativeIPv4Addresses = true,
        };
        // These packets are injected at the socket boundary to reproduce BSD's native
        // sockaddr sizes on every runner, including IPv6 after a shorter IPv4 address.
        await using var receiver = await IrohTransport.BindAsync(new IrohTransportOptions
        {
            PublishAddress = false,
            Network = Offline().Network with { UdpSocketFactory = _ => receiverSocket },
        });
        foreach (IPEndPoint from in new[]
        {
            new IPEndPoint(IPAddress.Loopback, 32001),
            new IPEndPoint(IPAddress.IPv6Loopback, 32002),
            new IPEndPoint(IPAddress.Loopback, 32003),
        })
        {
            byte[] payload = from.Port == 32001 ? [] : RandomNumberGenerator.GetBytes(1200);
            receiverSocket.Enqueue(from, payload);
            IrohDatagram received = await receiver.ReceiveAsync().AsTask().WaitAsync(Budget);
            Assert.Equal(from, received.Path.DirectAddress);
            Assert.Equal(payload, received.Payload.ToArray());
        }
    }

    [Fact]
    public async Task RawRelay_IsIdentityRouted_AndDoesNotRequirePinholeHeaders()
    {
        await using var server = new FakeIrohRelay();
        var network = Offline().Network with { IrohRelayUrls = [server.Url] };
        await using var a = await IrohTransport.BindAsync(new IrohTransportOptions { Network = network, PublishAddress = false });
        await using var b = await IrohTransport.BindAsync(new IrohTransportOptions { Network = network, PublishAddress = false });
        var relayOnly = new IrohAddress(b.EndpointId, relayUrls: [server.Url]);
        IrohRoute route = await a.ConnectAsync(relayOnly.ToString());
        Assert.Throws<ArgumentException>(() => a.SendTo(route.Paths[0], []));
        foreach (byte[] payload in new byte[][] { [1], [0xc0, 0, 0, 0, 1], "an application protocol owns these bytes"u8.ToArray() })
        {
            route.Send(payload);
            IrohDatagram atB = await b.ReceiveAsync().AsTask().WaitAsync(Budget);
            Assert.Equal(payload, atB.Payload.ToArray());
            Assert.Equal(a.EndpointId, atB.Path.EndpointId);
            Assert.Equal(server.Url, atB.Path.RelayUrl);
            Assert.Null(atB.Path.DirectAddress);
            b.SendTo(atB.Path, payload);
            Assert.Equal(payload, (await a.ReceiveAsync().AsTask().WaitAsync(Budget)).Payload.ToArray());
        }
        Assert.Contains(server.Forwarded, p => p.AsSpan().SequenceEqual("an application protocol owns these bytes"u8));
    }

    [Fact]
    public async Task DefaultSignedIrohDiscovery_PublishesAndDialsById_RejectsTamperAndRollback()
    {
        using var service = new MemoryPkarr();
        var publisherOptions = new IrohTransportOptions
        {
            Network = Offline().Network, DiscoveryHandler = service,
        };
        await using var publisher = await IrohTransport.BindAsync(publisherOptions);
        await using var dialer = await IrohTransport.BindAsync(new IrohTransportOptions
        {
            Network = Offline().Network, DiscoveryHandler = service, PublishAddress = false,
        });
        byte[] original = service.Payload!.ToArray();
        IrohAddress discovered = await dialer.ResolveAsync(publisher.EndpointId);
        Assert.Equal(publisher.EndpointId, discovered.EndpointId);
        Assert.Contains(discovered.DirectAddresses, x => x.Port == publisher.LocalPort);
        Assert.EndsWith(IrohEncoding.Encode32(Convert.FromHexString(publisher.EndpointId), zbase: true), service.LastUrl!.AbsolutePath);
        IrohRoute route = await dialer.ConnectAsync(publisher.EndpointId);
        route.Send("found through native iroh discovery"u8);
        Assert.Equal("found through native iroh discovery"u8.ToArray(),
            (await publisher.ReceiveAsync().AsTask().WaitAsync(Budget)).Payload.ToArray());

        service.Payload![^1] ^= 1;
        await Assert.ThrowsAsync<InvalidDataException>(() => dialer.ResolveAsync(publisher.EndpointId));
        await publisher.PublishAddressAsync();
        await dialer.ResolveAsync(publisher.EndpointId);
        service.Payload = original;
        await Assert.ThrowsAsync<InvalidDataException>(() => dialer.ResolveAsync(publisher.EndpointId));
        // A valid record for another endpoint is also rejected against this ID's key.
        string stranger = Convert.ToHexString(new RelayIdentity().PublicKey);
        await Assert.ThrowsAsync<InvalidDataException>(() => dialer.ResolveAsync(stranger));
    }

    [Fact]
    public async Task PublicationOptOut_DoesNotContactTheService()
    {
        using var service = new MemoryPkarr();
        await using var transport = await IrohTransport.BindAsync(new IrohTransportOptions
        {
            Network = Offline().Network, DiscoveryHandler = service, PublishAddress = false,
        });
        Assert.Equal(0, service.PutAttempts);
        Assert.Null(service.Payload);
    }

    [Fact]
    public async Task DirectAddressOptOut_PublishesOnlyRelayReachability()
    {
        await using var relay = new FakeIrohRelay();
        using var service = new MemoryPkarr();
        await using var transport = await IrohTransport.BindAsync(new IrohTransportOptions
        {
            Network = Offline().Network with { IrohRelayUrls = [relay.Url] },
            DiscoveryHandler = service, PublishDirectAddresses = false,
        });
        IrohAddress record = IrohDiscovery.ParsePayload(Convert.FromHexString(transport.EndpointId), service.Payload!, out _);
        Assert.Empty(record.DirectAddresses);
        Assert.Equal(relay.Url, Assert.Single(record.RelayUrls));
        Assert.Null(record.UserData); // raw UDP never claims an authenticated Pinhole session
    }

    [Fact]
    public async Task DiscoveryOutage_DoesNotPreventRawUdpTraffic()
    {
        using var service = new MemoryPkarr { RejectPuts = true };
        await using var listener = await IrohTransport.BindAsync(new IrohTransportOptions
        {
            Network = Offline().Network, DiscoveryHandler = service,
        });
        await using var dialer = await IrohTransport.BindAsync(Offline());
        Assert.Equal(1, service.PutAttempts);
        Assert.Null(service.Payload);
        IrohRoute route = await dialer.ConnectAsync(listener.Address.ToString());
        route.Send("direct despite discovery outage"u8);
        Assert.Equal("direct despite discovery outage"u8.ToArray(),
            (await listener.ReceiveAsync().AsTask().WaitAsync(Budget)).Payload.ToArray());
    }

    [Fact]
    public async Task RelayPreparation_CancellationAndDisposalStayBounded()
    {
        await using var transport = await IrohTransport.BindAsync(Offline());
        string peer = new IrohAddress(Convert.ToHexString(new RelayIdentity().PublicKey),
            relayUrls: [new Uri("http://127.0.0.1:1/")]).ToString();
        using var cancel = new CancellationTokenSource(TimeSpan.FromMilliseconds(150));
        await Assert.ThrowsAnyAsync<OperationCanceledException>(() => transport.ConnectAsync(peer, cancel.Token));
        Task<IrohDatagram> read = transport.ReceiveAsync().AsTask();
        await transport.DisposeAsync();
        await Assert.ThrowsAsync<ObjectDisposedException>(() => read.WaitAsync(Budget));
        Assert.Throws<ObjectDisposedException>(() => transport.SendTo(IrohPath.Direct(new IPEndPoint(IPAddress.Loopback, 42)), []));
    }

    [Fact]
    public async Task AlreadyCancelledDial_StopsEvenWhenItsTicketNeedsNoNetworkLookup()
    {
        await using var transport = await IrohTransport.BindAsync(Offline());
        using var cancelled = new CancellationTokenSource();
        cancelled.Cancel();
        await Assert.ThrowsAnyAsync<OperationCanceledException>(() => transport.ResolveAsync(NativeTicket, cancelled.Token));
        await Assert.ThrowsAnyAsync<OperationCanceledException>(() => transport.ConnectAsync(NativeTicket, cancelled.Token));
        await Assert.ThrowsAnyAsync<OperationCanceledException>(() => IrohTransport.BindAsync(Offline(), cancelled.Token));
    }

    private sealed class MemoryPkarr : HttpMessageHandler
    {
        public byte[]? Payload;
        public Uri? LastUrl;
        public bool RejectPuts { get; init; }
        public int PutAttempts;
        protected override async Task<HttpResponseMessage> SendAsync(HttpRequestMessage request, CancellationToken ct)
        {
            LastUrl = request.RequestUri;
            if (request.Method == HttpMethod.Put)
            {
                Interlocked.Increment(ref PutAttempts);
                if (RejectPuts) return new(HttpStatusCode.ServiceUnavailable);
                Payload = await request.Content!.ReadAsByteArrayAsync(ct);
            }
            return new HttpResponseMessage(HttpStatusCode.OK) { Content = new ByteArrayContent(Payload ?? []) };
        }
    }
}
