<Project>

	<PropertyGroup>
		<TreatWarningsAsErrors>true</TreatWarningsAsErrors>
		<Authors>IAFahim</Authors>
		<Version>1.9.0</Version>
		<PackageLicenseExpression>MIT</PackageLicenseExpression>
		<RepositoryUrl>https://github.com/IAFahim/Pinhole.Net</RepositoryUrl>
		<RepositoryType>git</RepositoryType>
		<PackageProjectUrl>https://github.com/IAFahim/Pinhole.Net</PackageProjectUrl>
		<NeutralLanguage>en</NeutralLanguage>
	</PropertyGroup>

</Project>
