<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<OutputType>Exe</OutputType>
		<TargetFramework>net10.0</TargetFramework>
		<IsPackable>false</IsPackable>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		
		<AssemblyName>pinhole-demo</AssemblyName>
		<PublishAot>true</PublishAot>
		<InvariantGlobalization>true</InvariantGlobalization>
	</PropertyGroup>

	<ItemGroup>
		<ProjectReference Include="../../src/Pinhole/Pinhole.csproj" />
		<ProjectReference Include="../../src/Pinhole.Turn/Pinhole.Turn.csproj" />
		<ProjectReference Include="../../src/Pinhole.Providers/Pinhole.Providers.csproj" />
	</ItemGroup>

</Project>
